#!/bin/sh
set -eu

value=${1-}
pattern='^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?(\+[0-9A-Za-z-]+(\.[0-9A-Za-z-]+)*)?$'
if [ ${#value} -gt 128 ] || ! printf '%s\n' "$value" | grep -Eq "$pattern"; then
	echo "VERSION must be a bounded SemVer value" >&2
	exit 2
fi
