package config

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"path/filepath"
	"time"

	"github.com/pelletier/go-toml/v2"

	"github.com/nysa-company/sf/internal/domain"
	"github.com/nysa-company/sf/internal/goclosure"
	"github.com/nysa-company/sf/internal/nodeclosure"
	"github.com/nysa-company/sf/internal/nysapure"
)

const MaxFileBytes = 64 * 1024

// NysaPureAPIV1Profile is the explicit, dependency-free TypeScript recipe
// used by the local Nysa compatibility slice. It is deliberately a profile
// name rather than a repository-specific path: the entrypoint is supplied by
// the project owner and frozen into the registered configuration snapshot.
const NysaPureAPIV1Profile = "nysa-api-pure-v1"

// ErrCommandDetection identifies a repository whose command contract needs an
// explicit .sf/config.toml. The CLI turns it into a channel-correct next
// action; callers can still distinguish it from malformed explicit config.
var ErrCommandDetection = errors.New("project command detection failed")

type machineDocument struct {
	MaxConcurrentTickets *int    `toml:"max_concurrent_tickets"`
	MaxPhaseTimeout      *string `toml:"max_phase_timeout"`
	MaxTicketTimeout     *string `toml:"max_ticket_timeout"`
	MaxTicketCostUSD     *int64  `toml:"max_ticket_cost_usd"`
	AllowAutonomous      *bool   `toml:"allow_autonomous"`
}

type projectDocument struct {
	BaseBranch           *string `toml:"base_branch"`
	MergeMode            *string `toml:"merge_mode"`
	MergeMethod          *string `toml:"merge_method"`
	MaxConcurrentTickets *int    `toml:"max_concurrent_tickets"`
	PhaseTimeout         *string `toml:"phase_timeout"`
	TicketTimeout        *string `toml:"ticket_timeout"`
	MaxTicketCostUSD     *int64  `toml:"max_ticket_cost_usd"`
	Commands             *struct {
		Verify []string `toml:"verify"`
		Review []string `toml:"review"`
	} `toml:"commands"`
	Providers *struct {
		Planner  []string `toml:"planner"`
		Builder  []string `toml:"builder"`
		Reviewer []string `toml:"reviewer"`
	} `toml:"providers"`
}

type nysaPureCommandsDocument struct {
	Verify []string `toml:"verify"`
	Review []string `toml:"review"`
}

type nysaPureConfigDocument struct {
	// The Node supervisor deliberately admits pure commands only up to one
	// minute. Keep a fresh generated profile inside that bound instead of
	// inheriting the general 45-minute project default.
	PhaseTimeout string                   `toml:"phase_timeout"`
	Commands     nysaPureCommandsDocument `toml:"commands"`
}

// NysaPureConfigPlan contains validated profile configuration that has not yet
// been installed. Keeping the generated bytes in memory lets callers complete
// all read-only repository and database checks before touching the checkout.
type NysaPureConfigPlan struct {
	Repository     string
	Path           string
	Commands       Commands
	Encoded        []byte
	Existing       bool
	prepared       []byte
	preparedDigest string
	preparedInfo   os.FileInfo
	installed      os.FileInfo
	lock           *nysaConfigLock
}

// PrepareNysaPureConfig validates the explicit Nysa profile without mutating
// the repository. An existing config must already contain the exact requested
// profile commands and is never replaced.
func PrepareNysaPureConfig(repository, profile, testPath string) (NysaPureConfigPlan, error) {
	plan := NysaPureConfigPlan{Repository: repository, Path: filepath.Join(repository, ".sf", "config.toml")}
	if profile == "" && testPath == "" {
		return plan, nil
	}
	if profile != NysaPureAPIV1Profile {
		return NysaPureConfigPlan{}, fmt.Errorf("unsupported project profile %q; supported profile is %s", profile, NysaPureAPIV1Profile)
	}
	if !nysapure.ValidTestPath(testPath) {
		return NysaPureConfigPlan{}, fmt.Errorf("profile %s requires a canonical repository-relative .test.ts path", profile)
	}
	lock, err := acquireNysaConfigLock(repository)
	if err != nil {
		return NysaPureConfigPlan{}, err
	}
	plan.lock = lock
	fail := func(err error) (NysaPureConfigPlan, error) {
		_ = plan.Close()
		return NysaPureConfigPlan{}, err
	}
	if err := nysapure.Validate(repository, testPath); err != nil {
		return fail(fmt.Errorf("validate %s test entrypoint: %w", profile, err))
	}

	data, exists, err := lock.readOptional("config.toml")
	if err != nil {
		return fail(err)
	}
	verify := []string{"node", nysapure.RecipeFlag, testPath}
	plan.Commands = Commands{Verify: Command{Argv: append([]string(nil), verify...)}, Review: Command{Argv: append([]string(nil), verify...)}}
	if exists {
		var document projectDocument
		if err := decodeStrict(data, &document); err != nil {
			return fail(fmt.Errorf("parse existing project configuration: %w", err))
		}
		if document.Commands == nil || !sameStrings(document.Commands.Verify, verify) || !sameStrings(document.Commands.Review, verify) {
			return fail(fmt.Errorf("existing .sf/config.toml has different commands; edit or remove it before selecting profile %s", profile))
		}
		plan.Existing = true
		plan.prepared = append([]byte(nil), data...)
		plan.preparedDigest = configDigest(data)
		plan.preparedInfo, err = lock.fileIdentity("config.toml")
		if err != nil {
			return fail(err)
		}
		return plan, nil
	}

	encoded, err := toml.Marshal(nysaPureConfigDocument{
		PhaseTimeout: "60s",
		Commands:     nysaPureCommandsDocument{Verify: verify, Review: verify},
	})
	if err != nil {
		return fail(fmt.Errorf("encode profile configuration: %w", err))
	}
	plan.Encoded = encoded
	return plan, nil
}

// ValidateUnchanged confirms that the file observed by Prepare or installed by
// Install is still the exact file that will be represented by the durable
// project snapshot. This closes the gap between repository/config validation
// and RegisterProject without replacing an owner's existing file.
func (plan *NysaPureConfigPlan) ValidateUnchanged() error {
	if plan == nil || (len(plan.Encoded) == 0 && !plan.Existing) {
		return nil
	}
	if plan.lock == nil {
		return errors.New("profile configuration lock is unavailable")
	}
	data, exists, err := plan.lock.readOptional("config.toml")
	if err != nil {
		return err
	}
	if !exists {
		return errors.New("profile configuration disappeared during initialization")
	}
	info, err := plan.lock.fileIdentity("config.toml")
	if err != nil {
		return err
	}
	if plan.Existing {
		if plan.preparedInfo == nil || !os.SameFile(plan.preparedInfo, info) || configDigest(data) != plan.preparedDigest || !bytes.Equal(data, plan.prepared) {
			return errors.New("profile configuration changed during initialization")
		}
		return nil
	}
	if plan.installed == nil || !os.SameFile(plan.installed, info) || !bytes.Equal(data, plan.Encoded) {
		return errors.New("installed profile configuration changed during initialization")
	}
	return nil
}

// Install installs a prepared profile config only when it was absent during
// preparation. It returns true only when this call created the file.
func (plan *NysaPureConfigPlan) Install() (bool, error) {
	if plan == nil {
		return false, errors.New("profile configuration plan is nil")
	}
	if plan.Existing || len(plan.Encoded) == 0 {
		return false, nil
	}
	if !filepath.IsAbs(plan.Repository) || filepath.Clean(plan.Repository) != plan.Repository || filepath.Clean(plan.Path) != plan.Path || filepath.Dir(plan.Path) != filepath.Join(plan.Repository, ".sf") || plan.lock == nil {
		return false, errors.New("profile configuration plan has an invalid repository path")
	}
	installed, err := plan.lock.install(plan.Encoded)
	if installed != nil {
		// A post-link verification failure can still return the exact temporary
		// inode so callers retain rollback authority until the .sf lock releases.
		plan.installed = installed
	}
	if err != nil {
		return plan.installed != nil, err
	}
	return true, nil
}

// Rollback removes only the newly-created config if it still has the same
// inode that Install placed. It never removes a pre-existing file or a
// concurrent replacement.
func (plan *NysaPureConfigPlan) Rollback() error {
	if plan == nil || plan.Existing || len(plan.Encoded) == 0 || plan.installed == nil {
		return nil
	}
	if plan.lock == nil {
		return errors.New("profile configuration lock is unavailable")
	}
	return plan.lock.rollback(plan.installed)
}

// Close releases the canonical .sf bootstrap lock. RunInit holds it through
// the final locked re-read and RegisterProject so concurrent initializers
// cannot split config admission from durable registration.
func (plan *NysaPureConfigPlan) Close() error {
	if plan == nil || plan.lock == nil {
		return nil
	}
	err := plan.lock.Close()
	plan.lock = nil
	return err
}

// EnsureNysaPureConfig preserves the original convenience API for callers
// that explicitly want to install the profile immediately.
func EnsureNysaPureConfig(repository, profile, testPath string) (bool, error) {
	plan, err := PrepareNysaPureConfig(repository, profile, testPath)
	if err != nil {
		return false, err
	}
	defer plan.Close()
	return plan.Install()
}

func sameStrings(left, right []string) bool {
	if len(left) != len(right) {
		return false
	}
	for index := range left {
		if left[index] != right[index] {
			return false
		}
	}
	return true
}

func configDigest(data []byte) string {
	sum := sha256.Sum256(data)
	return hex.EncodeToString(sum[:])
}

// LoadMachine reads an optional owner-local channel policy. A missing file is
// the conservative built-in policy; malformed or unknown fields fail closed.
func LoadMachine(path string) (MachineLimits, error) {
	limits := DefaultMachineLimits()
	data, exists, err := readOptionalConfig(path)
	if err != nil || !exists {
		return limits, err
	}
	var document machineDocument
	if err := decodeStrict(data, &document); err != nil {
		return MachineLimits{}, fmt.Errorf("parse machine configuration: %w", err)
	}
	if document.MaxConcurrentTickets != nil {
		limits.MaxConcurrentTickets = *document.MaxConcurrentTickets
	}
	if document.MaxPhaseTimeout != nil {
		limits.MaxPhaseTimeout, err = parseDuration("max_phase_timeout", *document.MaxPhaseTimeout)
		if err != nil {
			return MachineLimits{}, err
		}
	}
	if document.MaxTicketTimeout != nil {
		limits.MaxTicketTimeout, err = parseDuration("max_ticket_timeout", *document.MaxTicketTimeout)
		if err != nil {
			return MachineLimits{}, err
		}
	}
	if document.MaxTicketCostUSD != nil {
		limits.MaxTicketCostMicroUSD, err = dollarsToMicroUSD("max_ticket_cost_usd", *document.MaxTicketCostUSD)
		if err != nil {
			return MachineLimits{}, err
		}
	}
	if document.AllowAutonomous != nil {
		limits.AllowAutonomous = *document.AllowAutonomous
	}
	if err := validateMachine(limits); err != nil {
		return MachineLimits{}, err
	}
	return limits, nil
}

// LoadProject reads the optional committed .sf/config.toml and resolves it
// under machine policy. It returns canonical JSON bytes suitable for durable
// registration; raw TOML never becomes runtime authority.
func LoadProject(repository, name string, machine MachineLimits) (Effective, []byte, string, error) {
	return loadProject(repository, name, machine, nil)
}

// LoadProjectWithCommands resolves a prepared typed command pair without
// requiring that the corresponding repository config has been installed yet.
// This is used by explicit bootstrap flows to finish validation before their
// first repository mutation.
func LoadProjectWithCommands(repository, name string, machine MachineLimits, commands Commands) (Effective, []byte, string, error) {
	return loadProject(repository, name, machine, &commands)
}

func loadProject(repository, name string, machine MachineLimits, commandsOverride *Commands) (Effective, []byte, string, error) {
	data, exists, err := readOptionalConfig(filepath.Join(repository, ".sf", "config.toml"))
	if err != nil {
		return Effective{}, nil, "", err
	}
	return loadProjectData(repository, name, machine, commandsOverride, data, exists)
}

// LoadLockedProject re-reads a Nysa bootstrap configuration through the
// already-locked .sf directory descriptor. It is deliberately used immediately
// before RegisterProject rather than reopening a mutable repository pathname.
func (plan *NysaPureConfigPlan) LoadLockedProject(name string, machine MachineLimits, commandsOverride *Commands) (Effective, []byte, string, error) {
	if plan == nil || plan.lock == nil {
		return Effective{}, nil, "", errors.New("profile configuration lock is unavailable")
	}
	data, exists, err := plan.lock.readOptional("config.toml")
	if err != nil {
		return Effective{}, nil, "", err
	}
	return loadProjectData(plan.Repository, name, machine, commandsOverride, data, exists)
}

func loadProjectData(repository, name string, machine MachineLimits, commandsOverride *Commands, data []byte, exists bool) (Effective, []byte, string, error) {
	project := DefaultProject(name, repository)
	// Built-in defaults are conveniences, not a second policy layer. When the
	// owner-local machine policy is stricter, an otherwise empty repository
	// configuration inherits those caps rather than failing initialization.
	project.MaxConcurrentTickets = min(project.MaxConcurrentTickets, machine.MaxConcurrentTickets)
	project.PhaseTimeout = min(project.PhaseTimeout, machine.MaxPhaseTimeout)
	project.TicketTimeout = min(project.TicketTimeout, machine.MaxTicketTimeout)
	project.PhaseTimeout = min(project.PhaseTimeout, project.TicketTimeout)
	project.MaxTicketCostMicroUSD = min(project.MaxTicketCostMicroUSD, machine.MaxTicketCostMicroUSD)
	var err error
	var document projectDocument
	if exists {
		if err := decodeStrict(data, &document); err != nil {
			return Effective{}, nil, "", fmt.Errorf("parse project configuration: %w", err)
		}
		if commandsOverride == nil && (document.Commands == nil || document.Commands.Verify == nil || document.Commands.Review == nil) {
			detected, detectErr := detectRepositoryCommands(repository)
			if detectErr != nil {
				return Effective{}, nil, "", detectErr
			}
			if document.Commands == nil || document.Commands.Verify == nil {
				project.Commands.Verify = detected.Verify
			}
			if document.Commands == nil || document.Commands.Review == nil {
				project.Commands.Review = detected.Review
			}
		}
		if document.BaseBranch != nil {
			project.BaseBranch = *document.BaseBranch
		}
		if document.MergeMode != nil {
			project.MergeMode = domain.MergeMode(*document.MergeMode)
		}
		if document.MergeMethod != nil {
			project.MergeMethod = *document.MergeMethod
		}
		if document.MaxConcurrentTickets != nil {
			project.MaxConcurrentTickets = *document.MaxConcurrentTickets
		}
		if document.PhaseTimeout != nil {
			project.PhaseTimeout, err = parseDuration("phase_timeout", *document.PhaseTimeout)
			if err != nil {
				return Effective{}, nil, "", err
			}
		}
		if document.TicketTimeout != nil {
			project.TicketTimeout, err = parseDuration("ticket_timeout", *document.TicketTimeout)
			if err != nil {
				return Effective{}, nil, "", err
			}
		}
		if document.MaxTicketCostUSD != nil {
			project.MaxTicketCostMicroUSD, err = dollarsToMicroUSD("max_ticket_cost_usd", *document.MaxTicketCostUSD)
			if err != nil {
				return Effective{}, nil, "", err
			}
		}
		if document.Commands != nil {
			if document.Commands.Verify != nil {
				project.Commands.Verify = Command{Argv: append([]string(nil), document.Commands.Verify...)}
			}
			if document.Commands.Review != nil {
				project.Commands.Review = Command{Argv: append([]string(nil), document.Commands.Review...)}
			}
		}
		if document.Providers != nil {
			if document.Providers.Planner != nil {
				project.Providers.Planner = append([]string(nil), document.Providers.Planner...)
			}
			if document.Providers.Builder != nil {
				project.Providers.Builder = append([]string(nil), document.Providers.Builder...)
			}
			if document.Providers.Reviewer != nil {
				project.Providers.Reviewer = append([]string(nil), document.Providers.Reviewer...)
			}
		}
	} else if commandsOverride == nil {
		detected, detectErr := detectRepositoryCommands(repository)
		if detectErr != nil {
			return Effective{}, nil, "", detectErr
		}
		project.Commands = detected
	}
	if commandsOverride != nil {
		project.Commands = *commandsOverride
	}
	effective, err := Resolve(machine, project, TicketOverride{})
	if err != nil {
		return Effective{}, nil, "", err
	}
	snapshot, digest, err := Snapshot(effective)
	return effective, snapshot, digest, err
}

// detectRepositoryCommands selects only a small, typed walking-skeleton
// default. It intentionally refuses to guess for repositories whose build
// contract is not obvious; an explicit .sf/config.toml can opt into another
// argv-only command without adding shell interpretation.
func detectRepositoryCommands(repository string) (Commands, error) {
	goMod, err := regularRepositoryFile(filepath.Join(repository, "go.mod"), "go.mod")
	if err != nil {
		return Commands{}, err
	}
	packageJSON, err := regularRepositoryFile(filepath.Join(repository, "package.json"), "package.json")
	if err != nil {
		return Commands{}, err
	}
	if goMod && packageJSON {
		return Commands{}, detectionError("repository contains both go.mod and package.json; add explicit commands to .sf/config.toml")
	}
	if goMod {
		if _, err := goclosure.Validate(repository); err != nil {
			if errors.Is(err, goclosure.ErrUnvendored) {
				return Commands{}, detectionError("Go dependencies require checked-in vendor/modules.txt for local v1 verification; use operator or credential-free CI takeover")
			}
			return Commands{}, detectionError("go.mod is not a bounded dependency-free or vendored local verification closure; use operator or credential-free CI takeover")
		}
		command := Command{Argv: []string{"go", "test", "./..."}}
		return Commands{Verify: command, Review: command}, nil
	}
	if packageJSON {
		if err := nodeclosure.Validate(repository); err != nil {
			return Commands{}, detectionError("package.json is not the bounded dependency-free Node 22 local verification recipe; a configured nysa_api_pure_v1 path, npm/dependency-bearing project, or other recipe requires operator or credential-free CI takeover")
		}
		command := Command{Argv: []string{"node", "--test"}}
		return Commands{Verify: command, Review: command}, nil
	}
	return Commands{}, detectionError("repository type is unsupported; add explicit commands to .sf/config.toml")
}

func regularRepositoryFile(path, name string) (bool, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, detectionError("inspect " + name + " failed; add explicit commands to .sf/config.toml")
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return false, detectionError(name + " must be a regular non-symlink file; add explicit commands to .sf/config.toml")
	}
	if !info.Mode().IsRegular() {
		return false, detectionError(name + " must be a regular file; add explicit commands to .sf/config.toml")
	}
	return true, nil
}

func readBoundedRepositoryFile(path string, limit int64) ([]byte, error) {
	before, err := os.Lstat(path)
	if err != nil || before.Mode()&os.ModeSymlink != 0 || !before.Mode().IsRegular() {
		return nil, errors.New("repository marker is not a regular non-symlink file")
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	opened, err := file.Stat()
	if err != nil || !opened.Mode().IsRegular() || !os.SameFile(before, opened) {
		return nil, errors.New("repository marker changed while opening")
	}
	data, err := io.ReadAll(io.LimitReader(file, limit+1))
	if err != nil || int64(len(data)) > limit {
		return nil, errors.New("repository file exceeds bound")
	}
	return data, nil
}

func detectionError(message string) error {
	return fmt.Errorf("%w: %s", ErrCommandDetection, message)
}

func readOptionalConfig(path string) ([]byte, bool, error) {
	info, err := os.Lstat(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil, false, nil
	}
	if err != nil {
		return nil, false, fmt.Errorf("inspect configuration: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return nil, false, fmt.Errorf("configuration must be a regular non-symlink file")
	}
	parent, err := os.Lstat(filepath.Dir(path))
	if err != nil || parent.Mode()&os.ModeSymlink != 0 || !parent.IsDir() {
		return nil, false, fmt.Errorf("configuration parent must be a real directory")
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, false, fmt.Errorf("open configuration: %w", err)
	}
	defer file.Close()
	opened, err := file.Stat()
	if err != nil || !opened.Mode().IsRegular() || !os.SameFile(info, opened) {
		return nil, false, fmt.Errorf("configuration identity changed while opening")
	}
	reader := io.LimitReader(file, MaxFileBytes+1)
	data, err := io.ReadAll(reader)
	if err != nil {
		return nil, false, fmt.Errorf("read configuration: %w", err)
	}
	if len(data) > MaxFileBytes {
		return nil, false, fmt.Errorf("configuration exceeds %d bytes", MaxFileBytes)
	}
	return data, true, nil
}

func configFileIdentity(path string) (os.FileInfo, error) {
	info, err := os.Lstat(path)
	if err != nil {
		return nil, fmt.Errorf("inspect configuration: %w", err)
	}
	if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
		return nil, errors.New("configuration must be a regular non-symlink file")
	}
	return info, nil
}

func decodeStrict(data []byte, target any) error {
	decoder := toml.NewDecoder(bytes.NewReader(data)).DisallowUnknownFields()
	if err := decoder.Decode(target); err != nil {
		return err
	}
	return nil
}

func parseDuration(name, value string) (time.Duration, error) {
	duration, err := time.ParseDuration(value)
	if err != nil || duration <= 0 {
		return 0, fmt.Errorf("%s must be a positive Go duration", name)
	}
	return duration, nil
}

func dollarsToMicroUSD(name string, dollars int64) (int64, error) {
	if dollars <= 0 || dollars > math.MaxInt64/1_000_000 {
		return 0, fmt.Errorf("%s must be a positive whole-dollar value", name)
	}
	return dollars * 1_000_000, nil
}
